const topMenuMenu = [
  [
    "New Finder Window",
    "New Folder",
    "New Folder with Selection",
    "New Smart Folder",
    "New Tab",
    "Open",
    "Open With",
    "Print",
    "Close Window",
    "Get Info",
    "Rename",
    "Compress",
    "Duplicate",
    "Make Alias",
    "Quick Look",
    "Show Original",
    "Add to Sidebar",
    "Move to Trash",
    "Eject",
    "Find",
    "Tags",
  ],
  [
    "Undo",
    "Redo",
    "Cut",
    "Copy",
    "Paste",
    "Select All",
    "Show Clipboard",
    "Start Dictation...",
    "Emoji & Symbols",
  ],
  [
    "As Icons",
    "As List",
    "As Columns",
    "As Gallery",
    "Use Stacks",
    "Sort By",
    "Clean Up",
    "Clean Up By",
    "Hide Sidebar",
    "Show Preview",
    "Hide Toolbar",
    "Show All Tabs",
    "Show Tab Bar",
    "Show Path Bar",
    "Show Status Bar",
    "Customize Toolbar...",
    "Show View Options",
    "Show Preview Options",
    "Enter Full Screen",
  ],
  [
    "Back",
    "Forward",
    "Enclosing Folder",
    "Recents",
    "Documents",
    "Desktop",
    "Downloads",
    "Home",
    "Computer",
    "Airdrop",
    "Network",
    "iCloud Drive",
    "Applications",
    "Utilities",
    "Go to Folder",
    "Connect to Server",
  ],
];

export default topMenuMenu;